services:
  postgres:
    image: postgres:16
    container_name: clientes-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - clientes-api-postgres-data:/var/lib/postgresql/data

volumes:
  clientes-api-postgres-data: